'express'
Siarhei-Balonikau/node-mentoring pull request #4
Opened 2018-06-05 11:11 UTC by Siarhei-Balonikau

2018-06-05 11:38 UTC, slowpokex requested changes
Please correct your hometask

2018-06-05 11:38 UTC, slowpokex commented on http-servers/echo-server.js
> +.on('request', function (req, res) {
(req, res) => req.pipe(res)
Please prefer arrow functions

2018-06-05 11:38 UTC, slowpokex commented on src/controllers/index.js
> +exports.getAllProducts = function(req, res) {
please convert all to arrow functions

2018-06-05 11:38 UTC, slowpokex commented on src/middlewares/parse-query.js
> +const parseQuery = function (req, res, next) {
parse(req.url, true)

2018-06-05 11:38 UTC, slowpokex commented on src/routes/index.js
> +router.get('/products', controllers.getAllProducts);
Please chain it

2018-06-08 13:43 UTC, Siarhei-Balonikau commented on http-servers/echo-server.js
> +.on('request', function (req, res) {
Done

2018-06-08 13:44 UTC, Siarhei-Balonikau commented on src/controllers/index.js
> +exports.getAllProducts = function(req, res) {
Done

2018-06-08 13:53 UTC, Siarhei-Balonikau commented on src/routes/index.js
> +router.get('/products', controllers.getAllProducts);
Done

2018-06-19 16:30 UTC, merged